logging:
  config: classpath:logback-dev.xml
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portal2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: bill
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: biao.chenit@qq.com #QQ邮箱
    password: atlvzzlyladkbgaf #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: ${spring.mail.username} #与上面的username保持一致
---
app:
  file:
    path:
      root: